import { Platform, StyleSheet } from "react-native";
import { colors } from "./colors";

export const iconSizes = {
  header: 24,
  stat: 32,
  chevron: 24,
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray[50],
  },
  content: {
    padding: 20,
  },
  filterCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.primary,
    marginBottom: 20,
  },
  divider: {
    height: 1,
    backgroundColor: colors.gray[300],
    marginBottom: 20,
  },
  dividerCentral: {
    height: 1,
    backgroundColor: colors.gray[300],
    marginTop: 20,
    marginBottom: 20,
  },
  inputContainer: {
    flexDirection: "row",
    gap: 10,
  },
  input: {
    flex: 1,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.gray[300],
    borderRadius: 8,
    padding: 15,
    fontSize: 16,
    color: colors.black,
  },
  containerPicker: {
    padding: 20,
    justifyContent: "center",
  },
  label: {
    fontSize: 16,
    marginBottom: 8,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: colors.gray[300],
    borderRadius: 8,
    overflow: "hidden",
  },
  picker: {
    backgroundColor: colors.white,
    color: colors.black,
  },
  pickerInput: {
    fontSize: 16,
    paddingVertical: 15,
    paddingHorizontal: 15,
    paddingRight: 45,
    borderWidth: 1,
    borderColor: colors.gray[300],
    borderRadius: 8,
    color: colors.black,
    backgroundColor: colors.white,
  },
  pickerIconContainer: {
    top: Platform.OS === "ios" ? 15 : 15,
    right: 15,
  },
  pickerPlaceholder: {
    color: colors.gray[400],
  },
  pickerTouchable: {
    marginBottom: 20,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    marginBottom: 15,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: colors.gray[200],
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: colors.primary,
  },
  cardTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "bold",
    color: colors.primary,
    marginLeft: 10,
    marginRight: 10,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
  },
  statItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
  },
  statDivider: {
    width: 1,
    height: 60,
    backgroundColor: colors.gray[300],
  },
  statLabel: {
    fontSize: 12,
    color: colors.gray[600],
    marginTop: 8,
    fontWeight: "600",
    textAlign: "center",
  },
  statValue: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.black,
    marginTop: 4,
  },
  detailsButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.gray[100],
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4,
    flexShrink: 0,
  },
  detailsButtonText: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: 16,
    width: "95%",
    height: "85%",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 10,
    overflow: "hidden" as const,
    flexDirection: "column" as const,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
    marginBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: colors.primary,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.primary,
  },
  modalBody: {
    flex: 1,
  },
  modalBodyContent: {
    paddingBottom: 10,
    paddingHorizontal: 20,
  },
  detailSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
  },
  detailLabel: {
    fontSize: 16,
    color: colors.gray[600],
    fontWeight: "500",
  },
  detailValue: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.black,
  },
  modalCloseButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
    alignItems: "center",
    marginTop: 15,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  modalCloseButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "bold",
  },
  asistenciaItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    gap: 12,
  },
  asistenciaIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.gray[100],
    alignItems: "center",
    justifyContent: "center",
  },
  asistenciaInfo: {
    flex: 1,
  },
  asistenciaFecha: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.black,
    marginBottom: 4,
  },
  asistenciaDescripcion: {
    fontSize: 14,
    color: colors.gray[600],
  },
  asistenciaBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  asistenciaBadgeText: {
    fontSize: 12,
    fontWeight: "600",
  },
  retryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: colors.gray[100],
    borderRadius: 8,
  },
  retryButtonText: {
    fontSize: 14,
    color: colors.primary,
    fontWeight: "600",
  },
  loadingContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    backgroundColor: colors.white,
    borderRadius: 12,
    marginTop: 20,
  },
  loadingText: {
    fontSize: 16,
    color: colors.gray[600],
    marginTop: 12,
  },
  tableContainer: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: colors.gray[300],
    borderRadius: 8,
    overflow: "hidden" as const,
    backgroundColor: colors.white,
    width: "100%",
  },
  tableRow: {
    flexDirection: "row" as const,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray[200],
  },
  tableRowEven: {
    backgroundColor: colors.gray[50],
  },
  headerCell: {
    paddingVertical: 12,
    paddingHorizontal: 6,
    backgroundColor: colors.primary,
    borderRightWidth: 1,
    borderRightColor: colors.gray[300],
    flex: 1,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    minHeight: 50,
  },
  headerText: {
    color: colors.white,
    fontWeight: "700" as const,
    fontSize: 11,
    textAlign: "center" as const,
  },
  cell: {
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderRightWidth: 1,
    borderRightColor: colors.gray[200],
    flex: 1,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    backgroundColor: colors.white,
    minHeight: 45,
  },
  firstColumn: {
    flex: 1.1,
    justifyContent: "center" as const,
    alignItems: "flex-start" as const,
    paddingLeft: 10,
  },
  cellText: {
    fontSize: 12,
    fontWeight: "600" as const,
  },
  cellTimeText: {
    fontSize: 10,
    fontWeight: "400" as const,
    color: colors.gray[400],
    marginTop: 2,
  },
  cellValue: {
    fontSize: 15,
    fontWeight: "600" as const,
    color: colors.gray[600],
  },
});

export const pickerPropsIOS = {
  style: {
    backgroundColor: colors.white,
  },
  itemStyle: {
    color: colors.black,
    fontSize: 18,
  },
};
