import { StyleSheet } from "react-native";
import { colors } from "./colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.gray[100],
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    backgroundColor: colors.primary,
  },
  headerTitle: { fontSize: 18, fontWeight: "bold", color: colors.white },
  closeButton: { padding: 4 },
  scrollContent: { padding: 16 },
  reportHeader: {
    backgroundColor: colors.gray[50],
    padding: 12,
    borderRadius: 8,
    marginBottom: 12,
  },
  reportPeriod: { fontSize: 14, color: colors.gray[700], marginBottom: 4 },
  reportName: { fontSize: 16, fontWeight: "600", color: colors.gray[800] },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.gray[800],
    marginBottom: 12,
  },
  centerBox: { alignItems: "center", padding: 24 },
  textMuted: { fontSize: 14, color: colors.gray[700] },
  emptyStateBox: {
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
    marginTop: 60,
  },
  emptyStateTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.gray[800],
    marginTop: 20,
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 16,
    color: colors.gray[600],
    textAlign: "center",
    marginBottom: 4,
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: colors.gray[600],
    textAlign: "center",
    fontStyle: "italic",
  },
  noDataText: {
    fontStyle: "italic",
    color: colors.gray[700],
    textAlign: "center",
  },
  errorBox: {
    backgroundColor: colors.red[50],
    borderWidth: 1,
    borderColor: colors.red[100],
    borderRadius: 8,
    padding: 16,
    alignItems: "center",
  },
  errorText: { color: colors.red[700], marginBottom: 8, textAlign: "center" },
  retryButton: {
    backgroundColor: colors.primary,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  retryText: { color: colors.white, fontWeight: "500" },
  // Estilos para incidencias
  incidenciaCard: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  incidenciaHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  rowCenter: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    minWidth: 0,
  },
  incidenciaTitle: {
    marginLeft: 8,
    fontWeight: "600",
    fontSize: 15,
    flex: 1,
    flexWrap: "wrap",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  badgesContainer: {
    flexDirection: "column",
    gap: 6,
    alignItems: "flex-end",
  },
  chevronIcon: {
    marginLeft: 0,
  },
  severityBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    alignSelf: "flex-start",
  },
  severityBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
    alignSelf: "flex-start",
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: "600",
  },
  detailGroup: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.1)",
  },
  detailRow: {
    flexDirection: "row",
    marginBottom: 8,
    alignItems: "flex-start",
  },
  detailLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.gray[700],
    width: 110,
    flexShrink: 0,
  },
  detailValue: {
    fontSize: 13,
    color: colors.gray[800],
    flex: 1,
    flexWrap: "wrap",
  },
  // Descripción con borde naranja
  descripcionContainer: {
    flexDirection: "row",
    marginTop: 12,
    backgroundColor: colors.orange[50],
    borderRadius: 8,
    overflow: "hidden",
  },
  orangeBorder: {
    width: 4,
    backgroundColor: colors.orange[500],
  },
  descripcionContent: {
    flex: 1,
    padding: 12,
  },
  descripcionTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.orange[500],
    marginBottom: 6,
  },
  descripcionText: {
    fontSize: 13,
    color: colors.gray[700],
    lineHeight: 20,
  },
});
